### ISSUE TITLE
Copernicus Sentinel Data is now available on the Copernicus Data Space

### ISSUE THREAD

**Issue by robmarkcole** [allenai/vessel-detection-sentinels#9]
On running the download script:
```
sentinelsat.exceptions.ServerError: HTTP status 200 OK:
The Sentinels Scientific Data Hub

# Copernicus Sentinel Data is now available on the Copernicus Data Space
Ecosystem

[https://dataspace.copernicus.eu](https://dataspace.copernicus.eu/)
```

Tried updating the retrieve script:
```python
def retrieve(images, tmp_dir, download_dir, workers=0):
    """Retrieve images from ESA API."""
    api = SentinelAPI(
        os.environ.get("COPERNICUS_USERNAME"),
        os.environ.get("COPERNICUS_PASSWORD"),
        # "https://scihub.copernicus.eu/dhus",
        "https://dataspace.copernicus.eu/",
        timeout=60,
    )
```
error: 
```
⚡ master ~/vessel-detection-sentinels python download_imagery.py --save_dir="data"
2024-05-01 08:35:03,148 (downloader) (INFO): Collecting images corresponding to 39954 windows.
2024-05-01 08:35:03,285 (downloader) (INFO): Found 2913 such images to synchronize to local.

2024-05-01 08:35:03,285 (downloader) (INFO): Currently syncing 8 images...
2024-05-01 08:35:03,286 (downloader) (INFO): 0/8 already processed
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sentinelsat/sentinel.py", line 1023, in _check_scihub_response
    response.raise_for_status()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://dataspace.copernicus.eu/search?format=json&rows=100&start=0&q=filename%3A%22S1A_IW_GRDH_1SDV_20211105T024716_20211105T024741_040430_04CB0F_8DF4.SAFE%22
```

Tried:
- `"https://apihub.copernicus.eu/apihub",` -> times out
- `"https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/",` -> HTTP status 401 Unauthorized: Invalid API response

**Comment by Meenuth047** [comment]
May I know if the Copernicus Sentinel Data is now available on the Copernicus Data Space has been solved?
